version: '3.8'

services:
  mysql-usuarios:
    image: mysql:8
    container_name: mysql_usuarios
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3307:3306"
    volumes:
      - usuarios_data:/var/lib/mysql

  mysql-doctores:
    image: mysql:8
    container_name: mysql_doctores
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctores_db
    ports:
      - "3308:3306"
    volumes:
      - doctores_data:/var/lib/mysql

volumes:
  usuarios_data:
  doctores_data:
