apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.dbCredentials.rootPassword }}
  MYSQL_USERNAME: {{ .Values.dbCredentials.username }}
  MYSQL_PASSWORD: {{ .Values.dbCredentials.password }}
