apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuromotion-frontend.fullname" . }}-service
  namespace: ms-app
  labels:
    {{- include "neuromotion-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "neuromotion-frontend.selectorLabels" . | nindent 4 }}
