apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-doctores
  namespace: ms-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-doctores
