FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/ms-usuarios-0.0.1-SNAPSHOT.jar /app/ms-usuarios.jar

EXPOSE 8081

RUN apt-get update && apt-get install -y curl

ENTRYPOINT ["java", "-jar", "ms-usuarios.jar"]
