FROM node:20-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production --base-href /
RUN ls -l /app/dist/neuromotion-frontend # Add this line to inspect the build output

FROM nginx:alpine

COPY --from=build /app/dist/neuromotion-frontend/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
