apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios-config
  namespace: ms-app
data:
  APP_NAME: ms-usuarios
  SERVER_PORT: "8081"
  DB_URL: jdbc:mysql://mysql-usuarios:3306/db_usuarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  DDL_AUTO: update
  DB_PLATFORM: org.hibernate.dialect.MySQL8Dialect
  MS_DOCTORES_URL: http://ms-doctores-service:8082
  ACTUATOR_PORT: "8081"
