apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-doctores-config
  namespace: ms-app
data:
  APP_NAME: ms-doctores
  SERVER_PORT: "8082"
  DB_URL: jdbc:mysql://mysql-doctores:3306/doctores_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  DB_DRIVER: com.mysql.cj.jdbc.Driver
  DDL_AUTO: update
  DB_PLATFORM: org.hibernate.dialect.MySQL8Dialect
  ACTUATOR_PORT: "8082"
