apiVersion: v1
kind: Service
metadata:
  name: ms-usuarios-service
  namespace: ms-app
spec:
  selector:
    app: ms-usuarios
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
