apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-usuarios
  namespace: ms-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-usuarios
  template:
    metadata:
      labels:
        app: mysql-usuarios
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-usuarios-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: pvc-db-usuarios
