apiVersion: v1
kind: Service
metadata:
  name: mysql-usuarios
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql-usuarios
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
