apiVersion: v1
kind: Service
metadata:
  name: neuromotion-frontend-service
  namespace: ms-app
  labels:
    app: neuromotion-frontend
spec:
  type: NodePort
  selector:
    app: neuromotion-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 
